services:
  django:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
           gunicorn --bind 0.0.0.0:8000 wedding_card.wsgi:application"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: wedding_card.settings
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/usr/src/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - django

  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"