# Generated by Django 4.2.11 on 2024-05-17 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('imp_uid', models.CharField(max_length=200)),
                ('merchant_uid', models.CharField(max_length=200)),
                ('pay_method', models.CharField(max_length=50)),
                ('apply_num', models.CharField(max_length=200, null=True)),
                ('pg_provider', models.CharField(max_length=100)),
                ('buyer_name', models.CharField(max_length=200, null=True)),
                ('buyer_email', models.CharField(max_length=200, null=True)),
                ('pg_tid', models.CharField(max_length=200, null=True)),
                ('receipt_url', models.CharField(max_length=250, null=True)),
                ('card_name', models.CharField(max_length=200, null=True)),
                ('card_number', models.CharField(max_length=200, null=True)),
                ('success', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100, null=True)),
                ('paid_at', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
