# Generated by Django 4.2.11 on 2024-04-30 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='temp', max_length=20, null=True)),
                ('wedding_date', models.DateTimeField(null=True)),
                ('wedding_hall_address', models.CharField(max_length=100, null=True)),
                ('main_img', models.ImageField(null=True, upload_to='card/main/')),
                ('groom_name', models.CharField(max_length=20, null=True)),
                ('groom_mother_name', models.CharField(max_length=20, null=True)),
                ('groom_father_name', models.CharField(max_length=20, null=True)),
                ('groom_position', models.CharField(choices=[(0, '아들'), (1, '장남'), (2, '차남'), (3, '삼남'), (4, '사남'), (5, '독남'), (6, '막내'), (7, '조카'), (8, '손자'), (9, '동생')], default=0, max_length=10)),
                ('bride_name', models.CharField(max_length=20, null=True)),
                ('bride_mother_name', models.CharField(max_length=20, null=True)),
                ('bride_father_name', models.CharField(max_length=20, null=True)),
                ('bride_position', models.CharField(choices=[(0, '딸'), (1, '장녀'), (2, '차녀'), (3, '삼녀'), (4, '사녀'), (5, '독녀'), (6, '막내'), (7, '조카'), (8, '손녀'), (9, '동생')], default=0, max_length=10)),
                ('invitation_title', models.CharField(max_length=20, null=True)),
                ('invitation_comment', models.TextField(null=True)),
                ('thumb_img', models.ImageField(null=True, upload_to='card/thumb/')),
                ('thumb_title', models.CharField(max_length=20, null=True)),
                ('thumb_content', models.CharField(max_length=100, null=True)),
                ('guests_comment', models.CharField(default='temp', max_length=20, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
