# Generated by Django 4.2.11 on 2024-05-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='invitation_comment',
            new_name='invitation_content',
        ),
        migrations.AlterField(
            model_name='card',
            name='bride_position',
            field=models.CharField(choices=[('딸', '딸'), ('장녀', '장녀'), ('차녀', '차녀'), ('삼녀', '삼녀'), ('사녀', '사녀'), ('독녀', '독녀'), ('막내', '막내'), ('조카', '조카'), ('손녀', '손녀'), ('동생', '동생')], default='딸', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='groom_position',
            field=models.CharField(choices=[('아들', '아들'), ('장남', '장남'), ('차남', '차남'), ('삼남', '삼남'), ('사남', '사남'), ('독남', '독남'), ('막내', '막내'), ('조카', '조카'), ('손자', '손자'), ('동생', '동생')], default='아들', max_length=10),
        ),
    ]
