# Generated by Django 4.2.11 on 2024-05-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_rename_invitation_comment_card_invitation_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
