# Generated by Django 4.2.11 on 2024-05-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_card_created_at_alter_card_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='theme',
            field=models.CharField(choices=[('클래식', '클래식'), ('밤하늘', '밤하늘')], default='클래식', max_length=20, null=True),
        ),
    ]
