# Generated by Django 4.2.11 on 2024-06-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_card_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='wedding_hall_floor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='wedding_hall_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='bride_father_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='bride_mother_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='bride_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='groom_father_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='groom_mother_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='groom_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='invitation_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='invitation_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='card/main/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='theme',
            field=models.CharField(choices=[('클래식', '클래식'), ('밤하늘', '밤하늘')], default='클래식', max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='thumb_content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='thumb_img',
            field=models.ImageField(blank=True, null=True, upload_to='card/thumb/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='thumb_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='wedding_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='wedding_hall_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
