# Generated by Django 4.2.11 on 2024-06-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
