# Generated by Django 4.2.11 on 2024-06-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bride_position',
            field=models.CharField(blank=True, choices=[('딸', '딸'), ('장녀', '장녀'), ('차녀', '차녀'), ('삼녀', '삼녀'), ('사녀', '사녀'), ('독녀', '독녀'), ('막내', '막내'), ('조카', '조카'), ('손녀', '손녀'), ('동생', '동생')], default='딸', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='groom_position',
            field=models.CharField(blank=True, choices=[('아들', '아들'), ('장남', '장남'), ('차남', '차남'), ('삼남', '삼남'), ('사남', '사남'), ('독남', '독남'), ('막내', '막내'), ('조카', '조카'), ('손자', '손자'), ('동생', '동생')], default='아들', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='theme',
            field=models.CharField(blank=True, choices=[('클래식', '클래식'), ('밤하늘', '밤하늘')], default='클래식', max_length=20, null=True),
        ),
    ]
