# Generated by Django 4.2.11 on 2024-07-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_alter_card_main_img_alter_card_thumb_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='card/main/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='thumb_img',
            field=models.ImageField(blank=True, null=True, upload_to='card/thumb/'),
        ),
    ]
