# Generated by Django 4.2.11 on 2024-05-03 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0002_rename_invitation_comment_card_invitation_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestbooks', to='card.card')),
            ],
        ),
    ]
