# Generated by Django 4.2.11 on 2024-05-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
