# Generated by Django 4.2.11 on 2024-05-08 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0002_alter_guestbook_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
