# Generated by Django 4.2.11 on 2024-05-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_notice',
            field=models.BooleanField(default=False),
        ),
    ]
